### ISSUE TITLE
Caused by: org.apache.maven.model.building.ModelBuildingException - 'dependencies.dependency.version' for jdk.tools:jdk.tools:jar is missing

### ISSUE THREAD

**Issue by djuang1** [djuang1/parquet#1]
If you see the following error below in Anypoint Studio after you add the dependency to your pom.xml file, you need to edit the pom.xml for the audience-annotations file.

You can find that here: `<User Folder>/.m2/repository/org/apache/yetus/audience-annotations/0.11.0/audience-annotations-0.11.0.pom`. Just remove the <dependencies> section. This has been reported [here](http://mail-archives.apache.org/mod_mbox/yetus-notifications/201911.mbox/%3CJIRA.13246607.1563898455000.203016.1574535240218@Atlassian.JIRA%3E).

```
Failed to resolve module com.dejim:parquet:1.0.7-SNAPSHOT (hover for more details or open this problem's Properties)
Resolving dependency com.dejim:parquet found the following exceptions:
org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at com.dejim:parquet:jar:mule-plugin:1.0.7-SNAPSHOT -> org.apache.parquet:parquet-common:jar:1.11.0 -> org.apache.yetus:audience-annotations:jar:0.11.0
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:380)
	at org.mule.maven.client.internal.AetherMavenClient.doResolveDependencies(AetherMavenClient.java:479)
	at org.mule.maven.client.internal.AetherMavenClient.doResolveDependencies(AetherMavenClient.java:422)
	at org.mule.maven.client.internal.AetherMavenClient.resolvePluginBundleDescriptorsDependencies(AetherMavenClient.java:366)
	at org.mule.tooling.core.m2.internal.MuleMavenClientResolver.resolvePluginDependencies(MuleMavenClientResolver.java:78)
	at org.mule.tooling.core.module.internal.runner.DownloadTask.doRun(DownloadTask.java:76)
	at org.mule.tooling.core.module.internal.runner.Task.run(Task.java:65)
	at org.mule.tooling.core.module.internal.runner.DownloadTask.run(DownloadTask.java:1)
	at org.mule.tooling.core.module.internal.runner.SingleDownloadTask.run(SingleDownloadTask.java:1)
	at org.mule.tooling.core.module.internal.runner.ArtifactResolvingRunner$ArtifactJob.run(ArtifactResolvingRunner.java:220)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at com.dejim:parquet:jar:mule-plugin:1.0.7-SNAPSHOT -> org.apache.parquet:parquet-common:jar:1.11.0 -> org.apache.yetus:audience-annotations:jar:0.11.0
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	... 10 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.apache.yetus:audience-annotations:jar:0.11.0
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:338)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:504)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:504)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
	... 11 more
Caused by: org.apache.maven.model.building.ModelBuildingException: 2 problems were encountered while building the effective model for org.apache.yetus:audience-annotations:0.11.0
[ERROR] 'dependencies.dependency.version' for jdk.tools:jdk.tools:jar is missing. @ 
[ERROR] 'dependencies.dependency.systemPath' for jdk.tools:jdk.tools:jar is missing. @ 

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:479)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:421)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:411)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:320)
	... 26 more
```

**Comment by spandharpurkar-goodrx** [comment]
Hi @djuang1, the solution works fine for Anypoint Studio but we are getting the same issue while deploying MuleSoft  Application using CodeFresh CICD Pipeline. The application fails at the time of 'Build' with the same error. We are using Parquet Connector version 1.0.6-SNAPSHOT. Could you please help us so that we can deploy the application using CICD?
